### PR TITLE
Update ad-leap-seconds.adoc

### PR DESCRIPTION
**Pull request by sla29970**
include 5 most recent leap seconds

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]
Thanks, all these changes are spot on. Could you perhaps add more references to the definitions maybe? Either way, I'll merge this PR and try to add the currently included references in the bibliography.

**Comment by sla29970** [comment]
On Mon 2021-02-01T02:33:11-0800 Ujjwal Sharma hath writ:
> Thanks, all these changes are spot on.  Could you perhaps add more
> references to the definitions maybe?  Either way, I'll merge this PR
> and try to add the currently included references in the bibliography.

I can cite sources for everything.  I am too familiar with the subject
to see where more sources are needed.  Feel free to ask me about
anything.

--
Steve Allen                    <sla@ucolick.org>              WGS-84 (GPS)
UCO/Lick Observatory--ISB 260  Natural Sciences II, Room 165  Lat  +36.99855
1156 High Street               Voice: +1 831 459 3046         Lng -122.06015
Santa Cruz, CA 95064           https://www.ucolick.org/~sla/  Hgt +250 m

**Comment by ryzokuken** [comment]
@sla29970 thanks! I meant the definitions contain phrases like `Resolution 1 of the 13th duration of 9,192,631,770 cycles of microwave light CGPM on 1967-10-13`. Are these resolutions available in the public domain that could be referenced here?

**Comment by sla29970** [comment]
On Mon 2021-02-01T09:14:09-0800 Ujjwal Sharma hath writ:
> @sla29970 thanks!  I meant the definitions contain phrases like
> `Resolution 1 of the 13th duration of 9,192,631,770 cycles of microwave light CGPM on 1967-10-13`.
> Are these resolutions available in the public domain that could be referenced here?

https://www.bipm.org/en/CGPM/db/13/1/

and the references therein which give the details of the proceedings
of the conference

--
Steve Allen                    <sla@ucolick.org>              WGS-84 (GPS)
UCO/Lick Observatory--ISB 260  Natural Sciences II, Room 165  Lat  +36.99855
1156 High Street               Voice: +1 831 459 3046         Lng -122.06015
Santa Cruz, CA 95064           https://www.ucolick.org/~sla/  Hgt +250 m

**Comment by ryzokuken** [comment]
Thanks a ton! I'll include this link for more curious readers :D

**Comment by sla29970** [comment]
On Mon 2021-02-01T10:01:03-0800 Ujjwal Sharma hath writ:
> Thanks a ton! I'll include this link for more curious readers :D

in short, looking backwards in time

The cesium SI second was not in practical use outside of laboratories
until 1972.  All civil timekeeping was based on the mean solar second.

The CGPM approved the cesium second as the SI second in 1967.
After that a letter from the head of the CIPM explained that the
ephemeris second still existed because CGPM did not abrogate the
definition of the ephemeris.  The definition of the ephemeris second
had come from outside the of the CIPM and CGPM, so they could not
abrogate the ephemeris second, they could merely make it not part of
SI.

remained in existence after 1967 but it was no longer part of the SI.

The CGPM approved the ephemeris second as the SI second in 1960, by
which time there was a practical way for a laboratory to reproduce
that SI second.

The CIPM approved the ephemeris second in 1956, but there was no
practical way for a laboratory to reproduce that second.

Before 1956 the CIPM acknowledged that the second was the mean solar
second.  This second was in practical use everywhere, but this was not
the SI second.  No action by the CIPM nor CGPM ever abrogated the use
of the mean solar second because no action by the CIPM nor CGPM had
ever approved the use of the mean solar second.

Taking this last with the context of the CIPM letter from 1967 it is
clear that the mean solar second remains a valid, but not SI, form of
measurement in any jurisdiction where its use has not been made
explicitly illegal as Germany did in 1969.  That action by Germany is
what led to UTC with leap seconds.


--
Steve Allen                    <sla@ucolick.org>              WGS-84 (GPS)
UCO/Lick Observatory--ISB 260  Natural Sciences II, Room 165  Lat  +36.99855
1156 High Street               Voice: +1 831 459 3046         Lng -122.06015
Santa Cruz, CA 95064           https://www.ucolick.org/~sla/  Hgt +250 m

**Pull request merged**
